### ISSUE TITLE
Add resources to WEB3 Roadmap

### ISSUE THREAD

**Issue by kartikver15gr8** [BuildersChain/Developers-Roadmap#21]
### Description

Add credible resources to WEB3 roadmap file

**Comment by AshirMehmood** [comment]
are we supposed to post a draft first?

**Comment by kartikver15gr8** [comment]
Nope!
Particularly you don't have to, just add some credible resources in it and please add authentic resources only.

**Comment by Obi72-maobi-code** [comment]
Hi @yashdev9274 I would like to provide resources for this issue

**Comment by yashdev9274** [comment]
Go ahead @Obi72-maobi-code
