### ISSUE TITLE
Link the Roadmaps to their directed paths

### ISSUE THREAD

**Issue by yashdev9274** [BuildersChain/Developers-Roadmap#23]
### Description

In this issue, pls make sure to link all the roadmaps mentioned in readme file this repo to its directed roadmap.

For eg. 

We have made [Frontend-Developer](https://github.com/BuildersChain/Developers-Roadmap/tree/main/Frontend-Developer) Roadmap, so link this [Frontend-Developer](https://github.com/BuildersChain/Developers-Roadmap/blob/main)
 Roadmap mentioned in the readme file to this respective roadmap

> So do this with all the roadmaps.

### Link this Roadmap

![image](https://user-images.githubusercontent.com/72986960/219948436-212411cd-0c67-423b-afc9-89fa5f6dcbbf.png)

### TO this path

![image](https://user-images.githubusercontent.com/72986960/219948423-02b0ee2c-b489-4ff3-9755-03ff2883f1a0.png)

### Additional information

This is just an example I have provides to you, so link all the roadmaps which we have mentioned in our repo

**Comment by the-amazing-atharva** [comment]
Hey @yashdev9274 I would like to work on this issue

**Comment by yashdev9274** [comment]
Hey sure go ahead  @the-amazing-atharva 😇
