### ISSUE TITLE
[FEATURE] Add resources to Full stack roadmap

### ISSUE THREAD

**Issue by Saikat-Mandal** [BuildersChain/Developers-Roadmap#55]
### Description

Resources for full stack roadmap .

**Comment by yashdev9274** [comment]
Hey @Saikat-Mandal how is it going with this issue!!!

**Comment by Saikat-Mandal** [comment]
@yashdev9274 actually my exams are going on , so i will be working from day after tommrow.

**Comment by Saikat-Mandal** [comment]
@yashdev9274 please do review this PR.
