### ISSUE TITLE
[DOCS] Remove unavailable roadmaps headings from readme

### ISSUE THREAD

**Issue by Soumya-Kushwaha** [BuildersChain/Developers-Roadmap#64]
### Description

The readme contains several roadmap names, some of which are unavailable in the repository and lead to a "File Not Found" page. They shall be removed.

**Comment by yashdev9274** [comment]
Do share path of that particular readme file

**Comment by Soumya-Kushwaha** [comment]
These roadmaps lead to nowhere

![image](https://user-images.githubusercontent.com/87495134/229295132-6b6b6c1a-a98c-435d-a85b-605f4176f40f.png)

![image](https://user-images.githubusercontent.com/87495134/229295225-d4cda1d3-1e82-41ed-9202-9a4bdf0124f4.png)

**Comment by yashdev9274** [comment]
You are right There Are Some Roadmaps Whose Paths Are Not Ready yet

**Comment by yashdev9274** [comment]
If you like to work on this issue then go ahead.... I'll assign it to you
